name: Generate index.md with file links

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # WICHTIG: Push-Berechtigung aktivieren

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate index.md with all supported file types
        run: |
          echo "# 📄 Dateiindex für chpf-dps/port-info" > index.md
          echo "" >> index.md
          find . -type f \( \
            -iname "*.doc" -o -iname "*.docx" -o -iname "*.rtf" -o -iname "*.txt" -o -iname "*.md" -o \
            -iname "*.xls" -o -iname "*.xlsx" -o -iname "*.ods" -o -iname "*.csv" -o \
            -iname "*.pdf" -o \
            -iname "*.xml" -o -iname "*.json" -o -iname "*.yaml" -o -iname "*.yml" \
          \) | sort | while read filepath; do
            cleanpath="${filepath#./}"
            url="https://raw.githubusercontent.com/${{ github.repository }}/main/$cleanpath"
            echo "- [$cleanpath]($url)" >> index.md
          done

      - name: Commit and push index.md
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.md
          if git diff --cached --quiet; then
            echo "Keine Änderungen – nichts zu committen."
          else
            git commit -m "🔄 Automatisch generierter Dateiindex"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
